#!/bin/zsh

# now run in ~/.xinitrc
# sxhkd &
~/.screenlayout/two-monitor-xorg.sh
lxqt-policykit-agent &

bspc monitor eDP1 -d I II III IV V
# external display is either DP1 (if plugged in on left side) or DP2 (if plugged in on right side)
connected=$(xrandr | grep ' connected' | awk '{print $1}' | tr '\n' ' ')
[[ $connected =~ DP2 ]] && external=DP2 || external=DP1
bspc monitor $external -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a pavucontrol state=floating
bspc rule -a blueman-manager state=floating
bspc rule -a VMD state=floating

picom --backend glx --vsync &
# ~/.fehbg &
wal -R & # otherwise background not set and polybar not launched...
feh --bg-fill $(cat ~/.cache/wal/wal) &
~/.config/polybar/launch.sh &
# rclone mount --daemon gdrive: ~/gdrive --vfs-cache-mode full &  
