#!/usr/bin/sh

sxhkd &
~/.screenlayout/two-monitor-xorg.sh

bspc monitor eDP1 -d I II III IV V
bspc monitor DP1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a pavucontrol state=floating
bspc rule -a blueman-manager state=floating
bspc rule -a VMD state=floating

picom --backend glx --vsync &
~/.fehbg &
# feh --bg-fill $(cat ~/.cache/wal/wal) &
~/.config/polybar/launch.sh &
rclone mount --daemon gdrive: ~/gdrive --vfs-cache-mode full &  
