#!/bin/zsh

# now run in ~/.xinitrc
sxhkd &
~/.screenlayout/two-monitor-xorg.sh
lxqt-policykit-agent &

bspc monitor eDP1 -d I II III IV V
# external display is either DP1 (if plugged in on left side) or DP2 (if plugged in on right side)
connected=$(xrandr | grep ' connected' | awk '{print $1}' | tr '\n' ' ')
[[ $connected =~ DP2 ]] && external=DP2 || external=DP1
bspc monitor $external -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

# names are the second class name given by xprop
bspc rule -a Pavucontrol state=floating center=true focus=on
bspc rule -a Blueman-manager state=floating center=true focus=on
bspc rule -a VMD state=floating
# for tdrop, st is given the name 'floating'
bspc rule -a floating state=floating center=true focus=on
bspc rule -a scratchpad state=floating center=true sticky=on hidden=on
bspc rule -a Cheese state=floating center=true focus=on

st -c scratchpad &

libinput-gestures &

picom --backend glx --vsync &
feh --bg-fill $(cat ~/.cache/wal/wal) &
~/.config/polybar/launch.sh
# polybar calls pywal, so now reset terminal colours
xrdb ~/.Xresources
# set screen brightness to 30%
light -S 30
rclone mount --daemon gdrive: ~/gdrive --vfs-cache-mode full
